from manim import *

class PresentationColors:
    BACKGROUND = BLACK
    TEXT_PRIMARY = WHITE
    TEXT_SECONDARY = LIGHT_GREY
    ACCENT_MAIN = "#8fe5d1"
    ACCENT_BULLISH = GREEN_C
    ACCENT_BEARISH = RED_C
    ACCENT_NEUTRAL = YELLOW_C
    SCANNER_BLUE = BLUE
    CODE_BACKGROUND = GREY_E

